In [165]:
import pandas as pd
import numpy as np

In [124]:
car=pd.read_csv("quikr_car.csv")


In [125]:
car.size

5352

In [126]:
car.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 892 entries, 0 to 891
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   name        892 non-null    object
 1   company     892 non-null    object
 2   year        892 non-null    object
 3   Price       892 non-null    object
 4   kms_driven  840 non-null    object
 5   fuel_type   837 non-null    object
dtypes: object(6)
memory usage: 41.9+ KB


In [10]:
car['year'].unique()

array(['2007', '2006', '2018', '2014', '2015', '2012', '2013', '2016',
       '2010', '2017', '2008', '2011', '2019', '2009', '2005', '2000',
       '...', '150k', 'TOUR', '2003', 'r 15', '2004', 'Zest', '/-Rs',
       'sale', '1995', 'ara)', '2002', 'SELL', '2001', 'tion', 'odel',
       '2 bs', 'arry', 'Eon', 'o...', 'ture', 'emi', 'car', 'able', 'no.',
       'd...', 'SALE', 'digo', 'sell', 'd Ex', 'n...', 'e...', 'D...',
       ', Ac', 'go .', 'k...', 'o c4', 'zire', 'cent', 'Sumo', 'cab',
       't xe', 'EV2', 'r...', 'zest'], dtype=object)

In [ ]:
#data quality 
#year has many non year values
#price has many non integer values
#km has to be removed  
#feul type nan values

In [12]:
car['Price'].unique()

array(['80,000', '4,25,000', 'Ask For Price', '3,25,000', '5,75,000',
       '1,75,000', '1,90,000', '8,30,000', '2,50,000', '1,82,000',
       '3,15,000', '4,15,000', '3,20,000', '10,00,000', '5,00,000',
       '3,50,000', '1,60,000', '3,10,000', '75,000', '1,00,000',
       '2,90,000', '95,000', '1,80,000', '3,85,000', '1,05,000',
       '6,50,000', '6,89,999', '4,48,000', '5,49,000', '5,01,000',
       '4,89,999', '2,80,000', '3,49,999', '2,84,999', '3,45,000',
       '4,99,999', '2,35,000', '2,49,999', '14,75,000', '3,95,000',
       '2,20,000', '1,70,000', '85,000', '2,00,000', '5,70,000',
       '1,10,000', '4,48,999', '18,91,111', '1,59,500', '3,44,999',
       '4,49,999', '8,65,000', '6,99,000', '3,75,000', '2,24,999',
       '12,00,000', '1,95,000', '3,51,000', '2,40,000', '90,000',
       '1,55,000', '6,00,000', '1,89,500', '2,10,000', '3,90,000',
       '1,35,000', '16,00,000', '7,01,000', '2,65,000', '5,25,000',
       '3,72,000', '6,35,000', '5,50,000', '4,85,000', '3,29,5

In [13]:
car['kms_driven'].unique()

array(['45,000 kms', '40 kms', '22,000 kms', '28,000 kms', '36,000 kms',
       '59,000 kms', '41,000 kms', '25,000 kms', '24,530 kms',
       '60,000 kms', '30,000 kms', '32,000 kms', '48,660 kms',
       '4,000 kms', '16,934 kms', '43,000 kms', '35,550 kms',
       '39,522 kms', '39,000 kms', '55,000 kms', '72,000 kms',
       '15,975 kms', '70,000 kms', '23,452 kms', '35,522 kms',
       '48,508 kms', '15,487 kms', '82,000 kms', '20,000 kms',
       '68,000 kms', '38,000 kms', '27,000 kms', '33,000 kms',
       '46,000 kms', '16,000 kms', '47,000 kms', '35,000 kms',
       '30,874 kms', '15,000 kms', '29,685 kms', '1,30,000 kms',
       '19,000 kms', nan, '54,000 kms', '13,000 kms', '38,200 kms',
       '50,000 kms', '13,500 kms', '3,600 kms', '45,863 kms',
       '60,500 kms', '12,500 kms', '18,000 kms', '13,349 kms',
       '29,000 kms', '44,000 kms', '42,000 kms', '14,000 kms',
       '49,000 kms', '36,200 kms', '51,000 kms', '1,04,000 kms',
       '33,333 kms', '33,600 kms', '5,

In [14]:
car['fuel_type'].unique()

array(['Petrol', 'Diesel', nan, 'LPG'], dtype=object)

# data cleaning

In [15]:
cardatabackup=car.copy

In [127]:
car=car[car['year'].str.isnumeric()]        #filtering out  the numeric data

In [128]:
car['year']=car['year'].astype(int)          # converting the year data type to int 

In [129]:
car.info()

<class 'pandas.core.frame.DataFrame'>
Index: 842 entries, 0 to 891
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   name        842 non-null    object
 1   company     842 non-null    object
 2   year        842 non-null    int32 
 3   Price       842 non-null    object
 4   kms_driven  840 non-null    object
 5   fuel_type   837 non-null    object
dtypes: int32(1), object(5)
memory usage: 42.8+ KB


In [104]:
car['Price']

0             80,000
1           4,25,000
2      Ask For Price
3           3,25,000
4           5,75,000
           ...      
886         3,00,000
888         2,60,000
889         3,90,000
890         1,80,000
891         1,60,000
Name: Price, Length: 842, dtype: object

In [130]:
car=car[car['Price']!='Ask For Price']

In [131]:
car['Price']=car['Price'].str.replace(',','').astype(int)

In [132]:
car.info()

<class 'pandas.core.frame.DataFrame'>
Index: 819 entries, 0 to 891
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   name        819 non-null    object
 1   company     819 non-null    object
 2   year        819 non-null    int32 
 3   Price       819 non-null    int32 
 4   kms_driven  819 non-null    object
 5   fuel_type   816 non-null    object
dtypes: int32(2), object(4)
memory usage: 38.4+ KB


In [133]:
car['kms_driven']=car['kms_driven'].str.get(0).str.replace(',','')

In [134]:
car=car[car['kms_driven'].str.isnumeric()]

In [135]:
car.info()

<class 'pandas.core.frame.DataFrame'>
Index: 817 entries, 0 to 889
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   name        817 non-null    object
 1   company     817 non-null    object
 2   year        817 non-null    int32 
 3   Price       817 non-null    int32 
 4   kms_driven  817 non-null    object
 5   fuel_type   816 non-null    object
dtypes: int32(2), object(4)
memory usage: 38.3+ KB


In [136]:
car['kms_driven']=car['kms_driven'].astype(int)

In [137]:
car.info()

<class 'pandas.core.frame.DataFrame'>
Index: 817 entries, 0 to 889
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   name        817 non-null    object
 1   company     817 non-null    object
 2   year        817 non-null    int32 
 3   Price       817 non-null    int32 
 4   kms_driven  817 non-null    int32 
 5   fuel_type   816 non-null    object
dtypes: int32(3), object(3)
memory usage: 35.1+ KB


In [138]:
car=car[~car['fuel_type'].isna()]

In [139]:
car['name']=car['name'].str.split(' ').str.slice(0,3).str.join(' ')

In [140]:
car

name   company  year   Price  kms_driven fuel_type
0       Hyundai Santro Xing   Hyundai  2007   80000           4    Petrol
1       Mahindra Jeep CL550  Mahindra  2006  425000           4    Diesel
3         Hyundai Grand i10   Hyundai  2014  325000           2    Petrol
4    Ford EcoSport Titanium      Ford  2014  575000           3    Diesel
6                 Ford Figo      Ford  2012  175000           4    Diesel
..                      ...       ...   ...     ...         ...       ...
883      Maruti Suzuki Ritz    Maruti  2011  270000           5    Petrol
885          Tata Indica V2      Tata  2009  110000           3    Diesel
886    Toyota Corolla Altis    Toyota  2009  300000           1    Petrol
888            Tata Zest XM      Tata  2018  260000           2    Diesel
889      Mahindra Quanto C8  Mahindra  2013  390000           4    Diesel

[816 rows x 6 columns]

In [141]:
car=car.reset_index(drop=True)

In [142]:
car

name   company  year   Price  kms_driven fuel_type
0       Hyundai Santro Xing   Hyundai  2007   80000           4    Petrol
1       Mahindra Jeep CL550  Mahindra  2006  425000           4    Diesel
2         Hyundai Grand i10   Hyundai  2014  325000           2    Petrol
3    Ford EcoSport Titanium      Ford  2014  575000           3    Diesel
4                 Ford Figo      Ford  2012  175000           4    Diesel
..                      ...       ...   ...     ...         ...       ...
811      Maruti Suzuki Ritz    Maruti  2011  270000           5    Petrol
812          Tata Indica V2      Tata  2009  110000           3    Diesel
813    Toyota Corolla Altis    Toyota  2009  300000           1    Petrol
814            Tata Zest XM      Tata  2018  260000           2    Diesel
815      Mahindra Quanto C8  Mahindra  2013  390000           4    Diesel

[816 rows x 6 columns]

In [143]:
car.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 816 entries, 0 to 815
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   name        816 non-null    object
 1   company     816 non-null    object
 2   year        816 non-null    int32 
 3   Price       816 non-null    int32 
 4   kms_driven  816 non-null    int32 
 5   fuel_type   816 non-null    object
dtypes: int32(3), object(3)
memory usage: 28.8+ KB


In [144]:
car=car[car['Price']<6e6].reset_index(drop=True)

In [145]:
car

name   company  year   Price  kms_driven fuel_type
0       Hyundai Santro Xing   Hyundai  2007   80000           4    Petrol
1       Mahindra Jeep CL550  Mahindra  2006  425000           4    Diesel
2         Hyundai Grand i10   Hyundai  2014  325000           2    Petrol
3    Ford EcoSport Titanium      Ford  2014  575000           3    Diesel
4                 Ford Figo      Ford  2012  175000           4    Diesel
..                      ...       ...   ...     ...         ...       ...
810      Maruti Suzuki Ritz    Maruti  2011  270000           5    Petrol
811          Tata Indica V2      Tata  2009  110000           3    Diesel
812    Toyota Corolla Altis    Toyota  2009  300000           1    Petrol
813            Tata Zest XM      Tata  2018  260000           2    Diesel
814      Mahindra Quanto C8  Mahindra  2013  390000           4    Diesel

[815 rows x 6 columns]

In [146]:
car.to_csv("Cleanedcar.csv")

# Model

In [147]:
X=car.drop(columns='Price')
Y=car['Price']

In [148]:
X

name   company  year  kms_driven fuel_type
0       Hyundai Santro Xing   Hyundai  2007           4    Petrol
1       Mahindra Jeep CL550  Mahindra  2006           4    Diesel
2         Hyundai Grand i10   Hyundai  2014           2    Petrol
3    Ford EcoSport Titanium      Ford  2014           3    Diesel
4                 Ford Figo      Ford  2012           4    Diesel
..                      ...       ...   ...         ...       ...
810      Maruti Suzuki Ritz    Maruti  2011           5    Petrol
811          Tata Indica V2      Tata  2009           3    Diesel
812    Toyota Corolla Altis    Toyota  2009           1    Petrol
813            Tata Zest XM      Tata  2018           2    Diesel
814      Mahindra Quanto C8  Mahindra  2013           4    Diesel

[815 rows x 5 columns]

In [149]:
Y

0       80000
1      425000
2      325000
3      575000
4      175000
        ...  
810    270000
811    110000
812    300000
813    260000
814    390000
Name: Price, Length: 815, dtype: int32

In [155]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
from sklearn.preprocessing import OneHotEncoder
from sklearn.pipeline import make_pipeline
from sklearn.compose import make_column_transformer

In [156]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2)

In [154]:
ohe=OneHotEncoder()
ohe.fit(X[['name','company','fuel_type']])

OneHotEncoder()

In [157]:
column_trans=make_column_transformer((OneHotEncoder(categories=ohe.categories_),['name','company','fuel_type']),
                                    remainder='passthrough')

In [158]:
lr=LinearRegression()

In [159]:
pipe=make_pipeline(column_trans,lr)

In [160]:
pipe.fit(X_train,Y_train)

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('onehotencoder',
                                                  OneHotEncoder(categories=[array(['Audi A3 Cabriolet', 'Audi A4 1.8', 'Audi A4 2.0', 'Audi A6 2.0',
       'Audi A8', 'Audi Q3 2.0', 'Audi Q5 2.0', 'Audi Q7', 'BMW 3 Series',
       'BMW 5 Series', 'BMW 7 Series', 'BMW X1', 'BMW X1 sDrive20d',
       'BMW X1 xDrive20d', 'Chevrolet Beat', 'Chevrolet Beat...
                                                                            array(['Audi', 'BMW', 'Chevrolet', 'Datsun', 'Fiat', 'Force', 'Ford',
       'Hindustan', 'Honda', 'Hyundai', 'Jaguar', 'Jeep', 'Land',
       'Mahindra', 'Maruti', 'Mercedes', 'Mini', 'Mitsubishi', 'Nissan',
       'Renault', 'Skoda', 'Tata', 'Toyota', 'Volkswagen', 'Volvo'],
      dtype=object),
                                                                            array(['Diesel', 'LPG', 'Petrol'], dtype=object)]),
                                                  ['name', 'company',
                                                   'fuel_type'])])),
                ('linearregression', LinearRegression())])

In [161]:
y_pred=pipe.predict(X_test)

In [163]:
r2_score(Y_test,y_pred)

0.5971849795297125

In [167]:
scores=[]
for i in range(1000):
    X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.1,random_state=i)
    lr=LinearRegression()
    pipe=make_pipeline(column_trans,lr)
    pipe.fit(X_train,Y_train)
    y_pred=pipe.predict(X_test)
    scores.append(r2_score(Y_test,y_pred))

In [172]:
pipe.predict(pd.DataFrame(columns=X_test.columns,data=np.array(['Maruti Suzuki Swift','Maruti',2019,100,'Petrol']).reshape(1,5)))

array([791935.41328147])

In [168]:
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.1,random_state=np.argmax(scores))
lr=LinearRegression()
pipe=make_pipeline(column_trans,lr)
pipe.fit(X_train,Y_train)
y_pred=pipe.predict(X_test)
r2_score(Y_test,y_pred)

0.9200956709392505

In [169]:
import pickle

In [170]:
pickle.dump(pipe,open('LinearRegressionModel.pkl','wb'))

In [174]:
pipe.predict(pd.DataFrame([['Maruti Suzuki Swift','Maruti',2018,10000,'Petrol']],columns=['name','company','year','kms_driven','fuel_type']))

array([39470632.50337574])

In [173]:
pipe.predict(pd.DataFrame(columns=['name','company','year','kms_driven','fuel_type'],data=np.array(['Maruti Suzuki Swift','Maruti',2019,100,'Petrol']).reshape(1,5)))

array([791935.41328147])